LOAD CSV with headers FROM 'https://raw.githubusercontent.com/gprakash/data/main/forecasts.csv' AS line
match p=(productLocation:ItemLocation {itemLocationKey: line.locationId + ':' + line.locationType + ':' + line.itemGovSystem + ':' + line.itemNumber + ':' + line.itemIndicator + ':' + line.itemChangeLevel})-[:CONTAINS*]->(y:ItemLocation) 
with reduce (forecast = productLocation.forecast, r in relations(p) | forecast * r.quantity * r.suppliersplitpercent) as forecast
set y.forecast = forecast
return reduce (lineage = '', x in nodes(p) | lineage + ':' + x.itemLocationKey) as Lineage, y.itemLocationKey, y.forecast
